exports.CLASSES = {
  BODY_TEXT: 'bodyTextComponent',
  CONTAINER: 'container',
  COUNTDOWN_COMPONENT_WRAPPER: 'countdownComponentWrapper',
  FOOTER: 'footer',
  GALLERY_IMAGE: 'image-gallery-image',
  GALLERY_IMAGE_CENTER: 'center',
  GALLERY_IMAGE_LEFT: 'left',
  GALLERY_IMAGE_RIGHT: 'right',
  HEADLINE: 'headline',
  PAGE_CONTENT: 'pageContent',
  RECIRCULATION: 'recirculationModule',
  SECTION_TITLE: 'sectionTitle',
  SHARE_COMPONENT: 'shareComponent',
};
