FROM node:6.7.0

MAINTAINER Sarah Mogin <mogin@work.co>

# Install app dependencies
RUN mkdir -p /cache/dev
ADD package.json /cache/dev

RUN mkdir -p /cache/prod
ADD package.json /cache/prod

RUN cd /cache/dev && npm install && \
  tar czf node_modules.tar.gz node_modules && \
  rm -rf node_modules
RUN cd /cache/prod && npm install --only=prod && \
  tar czf node_modules.tar.gz node_modules && \
  rm -rf node_modules

# Set workdir
WORKDIR /workdir

# TODO separate node modules

CMD tar xzf /cache/dev/node_modules.tar.gz && \
  npm run server-build && \
  cp package.json dist/ && \
  cp *.yml dist/ && \
  cp -a docker dist/ && \
  cd dist/ && \
  tar xzf /cache/prod/node_modules.tar.gz
